INSERT INTO my_laravel.joblists (job_name, job_rank, job_company, job_des, company_des, jobcategory_id) VALUES ('Senior Software Engineer-3D Computer Vision', 1, 'Nearmap', 'Nearmap captures and processes massive quantities of high-resolution aerial imagery using world-leading automated technology. Our latest camera systems deliver rich 3D capability and the potential for a large array of new products and analysis. We are loo', 'Nearmap is a global leader in the provision of geospatial map technology for business, enterprises and government customers. As a truly innovative company for technical disruption, Nearmap holds over a dozen international patents and has developed a solut', 2);
INSERT INTO my_laravel.joblists (job_name, job_rank, job_company, job_des, company_des, jobcategory_id) VALUES ('Power Programmer', 2, 'Infosys', 'Short Description: As a Power Programmer, you will have the opportunity to work on Large Scale Digital Platforms and market places on complex engineering projects using cloud native architecture. This is an opportunity for a hands on developer to work on ', 'About us   Infosys is a global leader in consulting, technology, and outsourcing and next-generation services. We enable clients in more than 50 countries to outperform the competition and stay ahead of the innovation curve. With US$9.50 bn in FY16 revenu', 2);
INSERT INTO my_laravel.joblists (job_name, job_rank, job_company, job_des, company_des, jobcategory_id) VALUES ('Service Desk Engineer', 3, 'Viatek Pty Ltd ', 'We are looking for highly motivated, driven Service Desk Engineers - Level 1, to join our growing teams in Melbourne and Sydney, supporting our managed services contracted clients.

The role of the Service Desk Engineer - Level 1 is critical to the grow', 'Viatek Technology has an enviable reputation for high standards in IT solutions and service delivery.  We have grown rapidly, and have embraced the cloud age with our own cloud services, we are continually expanding thanks to a portfolio of sought-after t', 2);
INSERT INTO my_laravel.joblists (job_name, job_rank, job_company, job_des, company_des, jobcategory_id) VALUES ('Maintenance Technician', 4, 'Kapsch TrafficCom AG  Company Location Melbourne, Australia', 'We have an opportunity for an experienced Maintenance Technician to join our professional team in Melbourne.
The technician will, as part of a team, provide technical service, ongoing support and maintenance of the tolling systems.
You will be actively ', 'Kapsch TrafficCom is a provider of intelligent transportation systems (ITS). Our systems employ information and communication technologies to support and optimize road transportation, including infrastructure, vehicles, users and industry. Our core busine', 2);
INSERT INTO my_laravel.joblists (job_name, job_rank, job_company, job_des, company_des, jobcategory_id) VALUES ('Technical Support Representative - (Japanese/English)', 5, 'OpenTable  Company Location Melbourne, AU', 'Reporting to the Technical Support Supervisor, the Technical Support Representative will be responsible to provide customer support to customers, answering complex questions on function and usage of products via telephone, email and/or Internet. S/he will', 'We love what can happen around the restaurant table. Since 1998, we’ve been committed to empowering that experience. From helping restaurants grow and run their businesses, to enabling diners to discover and book the perfect table every time they dine, ou', 2);
INSERT INTO my_laravel.joblists (job_name, job_rank, job_company, job_des, company_des, jobcategory_id) VALUES ('IT Manager', 6, 'Hare & Forbes Machineryhouse  Company Location Northmead, New South Wales, Australia', 'The Position

Located at our Northmead Head Office, we are seeking candidates for a newly created role for an IT Manager with a twist of Digital Marketing Management.

The Successful Candidate

The successful candidate will have experience in a Mana', 'Hare & Forbes Machineryhouse have been supplying NEW & USED Workshop & Engineering Equipment since 1930.  Foundation principles have not changed to this date - to offer one of Australia''s most extensive range of workshop machinery and machine tool accesso', 2);
INSERT INTO my_laravel.joblists (job_name, job_rank, job_company, job_des, company_des, jobcategory_id) VALUES ('Logistics Technician', 7, 'Interactive Pty Ltd  Company Location Sydney, AU', 'Are you looking for your next great career move, a place where you can thrive and make a difference? At Interactive we pride ourselves on having a great work culture and providing the best customer experience in the industry. That''s how we''ve achieved the', 'Established in 1988, Interactive is one of Australia’s leading IT service providers. We are the supplier of choice for critical Cloud and Managed Services, Data Centre, Business Continuity and Hardware Maintenance for more than 2000 of Australia’s most su', 2);
INSERT INTO my_laravel.joblists (job_name, job_rank, job_company, job_des, company_des, jobcategory_id) VALUES ('Desktop Technician', 8, 'Marsh & McLennan Companies  Company Location Melbourne, AU', 'The Distributed Operations (DO) team provides overall operational support to the Pacific fleet of desktops and associated services that are hosted in the Pacific offices.', 'Scientific Games is a leading innovator in the global lottery and regulated gaming industries. Beginning with the breakthrough technology that launched the world’s very first secure instant lottery game in 1974, the company has continued to advance the games, technology, programs, marketing research and security that have been a driving force behind the success of more than 300 customers on six continents over the last 40 years.  Through the knowledge and experience of over 3,500 employees, Scientific Games serves customers from advanced-technology manufacturing and operational facilities in North America, South America, Europe, Asia and Australia, with additional facilities located throughout the U.S. and around the world based on customer requirements.', 2);
INSERT INTO my_laravel.joblists (job_name, job_rank, job_company, job_des, company_des, jobcategory_id) VALUES ('Senior SQA Engineer', 9, 'Scientific Games  Company Location Sydney, AU', 'This position is responsible for developing and executing tests on new and existing products to ensure that they meet the requisite functional, technical, and regulatory compliance and maintain high overall product quality. Interface with Game/OS Development and other Product Development staff to resolve issues in a timely manner. Also responsible for having proficient understanding of the software test methodologies and procedures in order to ensure testing efficiency and high level of quality. Will participate in mentoring Associate SQA and SQA Engineers. Organize and lead inter-departmental project meetings.', 'Scientific Games is a leading innovator in the global lottery and regulated gaming industries. Beginning with the breakthrough technology that launched the world’s very first secure instant lottery game in 1974, the company has continued to advance the games, technology, programs, marketing research and security that have been a driving force behind the success of more than 300 customers on six continents over the last 40 years.  Through the knowledge and experience of over 3,500 employees, Scientific Games serves customers from advanced-technology manufacturing and operational facilities in North America, South America, Europe, Asia and Australia, with additional facilities located throughout the U.S. and around the world based on customer requirements.', 2);
INSERT INTO my_laravel.joblists (job_name, job_rank, job_company, job_des, company_des, jobcategory_id) VALUES ('Helpdesk Analyst', 10, 'Michael Page  Company Location Ultimo, AU', 'Permanent Full Time
Helpdesk Analyst
About Our Client
My client is a significant industry force today because of the principles established over 25 years ago.
Job Description
Provide Help Desk services to all users.
Creating materials for end-user frequently asked questions (FAQs).
Maintain and be familiar with system documentation and document control.
Under general supervision, provide technical software, hardware and network problem resolution to all computer users by performing question / problem diagnosis and guiding users through step-by-step solutions
Support Desktops and IT infrastructure including VOIP telecommunications, across 5 states including 6 to 10 remote site / project offices.', 'Welcome to the Michael Page global company profile.  Michael Page has four decades of expertise in professional services recruitment. We were established in London in 1976, and over this period we''ve grown organically to become one of the best-known and most respected consultancies, with an office network spanning six continents.   While size has its advantages, it doesn''t define us - the nature of our organic growth means that each new office is integrated into the region that it serves. It also means that as an employer looking to hire, or as a candidate aiming to grow your career you have the best of both worlds; a team that understands the market and geography you operate in, plus the resources and expertise of an international network at your disposal.  Our teams are broken down to focus on industry, assignment type, salary level and location, so your hiring requirements or job search will all be handled by a specialist who knows your sector inside-out. We are confident that our expertise can add value to your recruitment or job search process – get in touch to find out more.', 2);
INSERT INTO my_laravel.joblists (job_name, job_rank, job_company, job_des, company_des, jobcategory_id) VALUES ('Head of Art (Design Art Director)', 1, 'V.I.  Company Location Melbourne, Australia', 'Are you an Art Director with a flair for design and a hands-on attitude? Do you live and breath all things creative and have your finger on the pulse when it comes to design trends and innovations?

We''re looking for a leader who can work with our talented studio of Creatives and Designers to make great work happen. As a new role, it''s a big opportunity for a Designer / Art Director to get involved in the future direction of the agency. We''re on the hunt for an all-round gun with solid agency experience and a flair for problem solving and a background in design.

The successful applicant will need to have agency experience working with international brands and understand the challenges involved in producing outstanding and creative work that adheres to corporate style-guides.

We’re looking for a creative all-rounder with strong typographic skills and the ability to take an idea, run with it and turn it into a campaign. You care about craft and know your way around Creative Suite. You will need to have the attention to detail and focus to see jobs through to perfection. You will also need to be able to multi-task, direct others and work in a team.', 'A little about us: V.I. is a medium-sized full service creative agency located in the balmy ‘burbs of Albert Park, surrounded by good coffee and exceptional lunch options. We pride ourselves on our ability to work to tight deadlines without compromising on quality, while having fun and making sure we don’t take ourselves too seriously.', 1);
INSERT INTO my_laravel.joblists (job_name, job_rank, job_company, job_des, company_des, jobcategory_id) VALUES ('Art Director', 2, 'Leadbolt  Company Location Sydney Office', 'We are a mobile performance advertising company based in Sydney and looking for a talented and experienced Art Director to join us at Leadbolt, an award winning global mobile company.', 'Leadbolt is a high performance mobile advertising platform for user acquisition and in-app monetization. Powered by direct relationships and dynamic ad-serving technologies, Leadbolt allows mobile advertisers to reach and acquire quality users at scale. Leadbolt’s analytics-based algorithms assist advertisers with advanced targeting that captivates best-fit audiences to achieve deeper user engagement with maximum ROI.  For app developers, Leadbolt''s award winning Direct Deals Marketplace optimizes inventory and partner matching delivering high impact ad solutions in real time while maximizing in-app advertising performance.   Leadbolt delivers over 10 billion ads per month across 65,000 apps globally. Leadbolt is headquartered in Sydney, Australia with offices in Los Angeles and Bangalore. For more information, visit www.leadbolt.com', 1);
INSERT INTO my_laravel.joblists (job_name, job_rank, job_company, job_des, company_des, jobcategory_id) VALUES ('Graphic Designer', 3, 'Creative Recruiters Company Location Melbourne,Australia', 'Job description
Graphic Designer (Mid-Snr) | Freelance | Melbourne
Weekly Pay and Great Rates
Temporary Opportunities!
We are looking to build the biggest and best Temporary and Freelance Graphic Design team that Melbourne has to offer!
Creative Recruiters works at the heart of the creative community, connecting talented individuals with rewarding careers. That means working closely with start-ups, global corporations and everything in between. In doing so, we help both businesses and people to succeed.

If you''re a professional freelance Graphic Designer (all-rounder or specialised) with 3+ years commercial industry experience, then we’re keen to hear from you and to learn more about what kind of freelance work is going to really excite you.

In order to be eligible, you must have a minimum of 3+ years commercial industry experience, be capable of working on site in Melbourne, and be up to date with industry standard software, especially CS CC. You should have an up-to-date CV and a digital folio that showcases the range of work you''ve produced and your involvement in its creation.', 'Creative Recruiters provides leading businesses with creative talent — from print designers and directors to digital designers and developers, to communication and social media specialists, to production and account service teams.', 1);
INSERT INTO my_laravel.joblists (job_name, job_rank, job_company, job_des, company_des, jobcategory_id) VALUES ('Art Director', 4, 'Cotton On Group  Company Location Melbourne, Australia', 's Art Director, you are an organised graphic artist who can work independently and creatively to provide all departments with commercial artwork and a professional and artistic service

You are responsible for project managing design briefs from completion through to high quality print ready artwork and ensure concepts are on brand. Managing a team of designers acting as a mentor, leader and design guru inspiring your team to create amazing work while ensuring you are up to date with latest fashion trends, keeping design work fresh and innovative.

SKILLS & EXPERIENCE

You are degree qualified in Graphic Design and have proven communication, leadership and people-management skills.
You have previous experience managing a project based work log and strict timeline processors and communicating to other departments.', 'From market start up to global brand, the Cotton On Group now has 7 brands, over 1,300 stores and more than 20,000 passionate people working in 17 countries around the globe.  In the past 25 years we have become Australia''s largest value fashion brand. We foster innovation, new ideas and a fierce will to succeed.   We make the most of today and always look to tomorrow for new and exciting opportunities. We get involved, roll up our sleeves and make things happen. It''s our shared belief that we can make a difference to the lives of everyone we touch – from our backyard to the world.   Central to this is our Cotton On Foundation, the philanthropic arm of the Cotton On Group. Our people are our #1 Cotton On Foundation ambassadors – and all Cotton On Group team members generously and enthusiastically support and participate in all aspects of the Foundation.   The story is far from over.  The future is full of new opportunities and ideas.  Careers that start here, can go anywhere.', 1);
INSERT INTO my_laravel.joblists (job_name, job_rank, job_company, job_des, company_des, jobcategory_id) VALUES ('Senior Art Director', 5, 'eskimo  Company Location Sydney, Australia', 'eskimo is a creative consultancy delivering strategic design, art direction and communications for fashion, lifestyle, retail and property brands. We believe beautiful design in form and function has the power to transform a customer’s experience, no matter what the category.

We are looking for an exceptional Senior Art Director / Designer to join our team.

For this rare opportunity to work across our fashion and retail clients you will need to possess the following:

6+ years experience in delivering brand identities, campaigns, print and digital projects
Strategic, innovative and curious thinker
Proactive and responsible', 'eskimo is an independant creative agency and consultancy. We deliver strategic communications for fashion, retail and property brands.  We believe beautiful design in form and function has the power to transform a customers’ experience no matter what the category. With over 25 years of expertise across fashion and lifestyle categories, we bring a unique understanding of what it takes to create desirable communications consumers will aspire to.    A a hand-picked team of creative professionals, and a network of experienced specialists. Our world-class and award-winning work, enriches Australia’s leading companies.', 1);
INSERT INTO my_laravel.joblists (job_name, job_rank, job_company, job_des, company_des, jobcategory_id) VALUES ('Art Creative Director', 6, 'Map Talent Group  Company Location Sydney, Australia', 'Creative Director with strong knowledge of Digital

Based in the heart of Sydneys CBD group of like-minded free thinkers, that deliver award-winning campaigns. They combine insight driven strategy with award winning creative for premium brands and there own products.
Looking for a talented Creative Director with a proven track in leading creative teams to deliver pioneering ideas for big brands. You will be hungry to lead your own department and will be responsible for ensuring creative excellence throughout the agency with a huge amount of autonomy.
You''ll love:
* Inspiring and motivating a team. Building a strong creative culture in the agency making sure everyone strives to deliver the best possible work.
* Social - creating interesting and new ideas that help our client''s brands reach their consumers and drive action
* Work that works. Campaigns that meet the objectives of our clients, not just gimmicks', 'Bespoke talent provider; Digital, creative, delivery and product   We are people over process, we listen, we connect and we deliver results   Success is a journey, we create the Map   www.maptalent.com.au ', 1);
INSERT INTO my_laravel.joblists (job_name, job_rank, job_company, job_des, company_des, jobcategory_id) VALUES ('Integrated Designer / Finished Artist', 7, 'Saatchi & Saatchi  Company Location Melbourne, Australia', 'We are a Nothing Is Impossible company.

We simplify and solve business problems through the power of Organising Ideas

and applying the alchemy of creativity and innovation. We are result obsessed.


We are a diverse collective of creative souls; hungry for greatness, respectful of each other and optimistic in mindset. And we are looking for a dynamic Designer/Artworker to join our team in Melbourne.



The role:

Works under the day to day creative direction and mentorship of our Senior Digital Designer and Senior Designer
Works closely with our Group CD & Creative teams, our Lead Digital Designer, Producers and Vendors to bring all cross-channel campaign elements to life.', 'Saatchi & Saatchi has grown from a start-up advertising agency in London in 1970 to a global creative communications company headquartered in New York with 114 offices in 67 countries and over 6000 employees. Saatchi & Saatchi is part of the Publicis Groupe, the world’s third largest communications group. We are a full service, integrated communications network and we work with 6 of the top 10 and over half of the top 50 global advertisers. We’re in the business of getting people to fall in love with our clients’ products and services. Through our creative ideas across all media and all disciplines, we set out to turn brands into Lovemarks which, unlike brands, generate loyalty beyond reason. We believe passionately in the power of ideas to differentiate and motivate. And to change the world for the better. We have an unshakeable spirit and unbeatable attitude from day one at Saatchi & Saatchi that Nothing is Impossible.', 1);
INSERT INTO my_laravel.joblists (job_name, job_rank, job_company, job_des, company_des, jobcategory_id) VALUES ('
Share this to social media
Show more options
Open feedback dialog
Creative Graphic Designer - Marketing', 8, 'Target Australia  Company Location Geelong', 'Job description
Enjoy coming to work with highly creative, fast paced team
Produce creative advertising for one of Australia''a most loved brands
Opportunity of development in a large marketing team
Target is committed to providing an interactive and fully connected approach to our customers, continuing to offer products with the style, quality and affordability our customers expect every day through our network of over 300 stores and rapidly growing online presence.

We''re successful through the amazing people we have working for us and we''re proud of our commitment in supporting local and overseas communities and charities.

Part of Wesfarmers this is your chance to join a business that is moving forward, based at our Store Support Office in North Geelong moving to a brand new purpose built facility in Williams Landing (near Laverton) at the end of 2018.', 'Welcome to Target!   Our vision is simple: To provide our customers with quality fashion and basics for everyone at low prices.  An iconic Australian retailer, our story began in 1926 when George Lindsay and Alex McKenzie opened a drapery store in Geelong, Victoria with a focus on great quality and value. Over 90 years on, we’ve grown & evolved, but our philosophy remains the same.   Part of the Wesfarmers group, one of Australia’s largest employers, we’re immensely proud of our history and building our store network to over 300 stores across Australia and over 13,000 team members who work as part of the Target brand across our Store operations and in our Store Support Office in addition to our team based in our Asian sourcing offices.  ', 1);
INSERT INTO my_laravel.joblists (job_name, job_rank, job_company, job_des, company_des, jobcategory_id) VALUES ('Open feedback dialog
Overseas English Teacher / ESL Teacher - China', 9, 'EF English First  Company Location Melbourne, Australia', 'TEACH ENGLISH, TRAVEL AND TRAIN IN CHINA WHILE DEVELOPING YOUR CAREER IN EDUCATION.



Free flights to many locations across China for a limited time only.



We’re looking for amazing English teachers to join us in Shanghai, Beijing, and many other cities across China. Teach English at one of our kids and teens, adult, or online schools, and you will get a great salary and competitive benefits package. Meet people from all over the world, develop your career abroad in education, and enjoy the experience of a lifetime.', 'EF English First, a division of EF Education First, is the world''s leading privately owned education company. Founded in 1965, EF operates in over 50 countries around the world. We have vacancies for teaching positions across China, so if you prefer the fast paced city life of cities like Shanghai, or want to be immersed in the more traditional culture of a smaller city, we have the position for you.', 1);
INSERT INTO my_laravel.joblists (job_name, job_rank, job_company, job_des, company_des, jobcategory_id) VALUES ('WPP AUNZ - Head of Design & Studio', 10, 'WPP AUNZ  Company Location Melbourne, Australia', 'The Head of Design & Studio, Melbourne, will be the reporting line manager for all Design, Artwork, Retouching/CGI and Pre-press delivered by the integrated craft team based in Melbourne.

Working in partnership with Head of D&S Sydney, you will lead a local team which delivers Digital, Print and Motion design/art for all media (static and animated) and be expected to oversee activity schedules, approval milestones and creative outputs to ensure deadlines are met and high production values are delivered.
You’ll be a ‘hands-on’ practice expert, with deep expertise in both the craft and technical aspects of your team’s responsibilities. Strengths may exist in primary areas such as Design, Technical Finished Art, Pre-press and Print, however you will be multi-skilled across all forms of design and studio operations, including 2D/3D CGI, video and digital content.', 'We are in the process of aggregating a number of existing WPP AUNZ production businesses into one central entity. This group will initially comprise of over fifty employees and grow to over eighty by the end of 2017. The focus of the new entity will be the production and adaptation of advertising for national and global clients. We will do this across all media: TV, print, digital. Our production expertise coupled with our powerful workflow and asset management technology will deliver quality, control and savings for brands. We strive to bring innovation to the art and craft of advertising production.', 1);
INSERT INTO my_laravel.joblists (job_name, job_rank, job_company, job_des, company_des, jobcategory_id) VALUES ('Sales Manager', 1, 'Protech Group  Company Location Melbourne, Australia', 'The Company

A privately owned national business partnering with renowned builders providing equipment services on iconic projects across Australia. A specialist in their field predominately hiring out state of the art crane and hoist equipment. This is a unique opportunity to stamp your own footprint in this sector.



About the role

You will be responsible for fostering existing and building new relationships with construction clientele. Reporting into the Director you will develop sales in the Victorian region. This business already has strong relationships nationally so you will continue to develop warm leads whilst creating opportunities.', 'Protech provides leading, flexible and smart workforce solutions to the Civil Infrastructure, Construction, Engineering, Maintenance, Mining, Resources and Energy sectors.
 
 We deliver a seamless service to our clients by providing tailored, high quality, responsive temporary labour hire, recruitment and permanent placement solutions. We specialise in the supply of semi-skilled, skilled, technical, trades and professional personnel, and our rigorous Quality through Methodology approach ensures we deliver quality people, every time. 
 ', 3);
INSERT INTO my_laravel.joblists (job_name, job_rank, job_company, job_des, company_des, jobcategory_id) VALUES ('Sales Consultant', 2, 'Becks Wiggins Stokes Pty Ltd  Company Location Melbourne, Australia', 'An exceptional opportunity is on offer for an experienced Internal Sales Officer/Front Counter Officer to join this long established business supplying product to the Plaster industry. Dealing directly with the public your role will incorporate counter sales, you will be responsible for managing incoming customer queries via telephone, emails and face-face for walk-in clients.

The role is working on a rotating roster Monday to Friday from 630am to 5pm and on Saturday 7am to 12pm and you will only be working one in three Saturdays. This role is based in Clayton.

Reporting to the Operations Manager some of your core duties will include;



Developing excellent relationships with customers through providing outstanding customer service and follow up
Providing technical advice to customers', 'Becks Wiggins Stokes Pty Ltd (BWS Recruitment) has a long history of placing the right people in the rights jobs for over 21 years. The company has two locations, with our head office based in Melbourne and is owned and operated by Belinda Wiggins. The original business commenced operation in 1995 and over this time the firm has managed to maintain and grow its core value proposition and leadership status as a respected and experienced recruitment solutions firm.
 
 Having recently celebrated our 21st Birthday, we are delighted to continue to service our clients and candidates with the model of repeat business and referral work across both our Temporary & Permanent Divisions. We recruit each candidate as if we are recruiting for our own business and we set the bar high and work within best practice frameworks.', 3);
INSERT INTO my_laravel.joblists (job_name, job_rank, job_company, job_des, company_des, jobcategory_id) VALUES ('Sales Director', 3, 'Hays  Company Location Melbourne CBD, Melbourne, Australia', 'Your new company
You will be working for a developer who has cultivated an industry leading property development portfolio all over Australia. Their expansion has resulted in company growth allowing for this opportunity to emerge.
Your new role
As Sales Director for their Melbourne office you will be an integral part of the management team with responsibilities including the setting of the sales target of your in house sales team, recruiting and expanding your team and to work within the executive team to deliver an attractive company culture. You will also be a part of the development of their marketing strategy and use your knowledge of the industry to advise and implement strategies to keep up with local and international trends.', 'POWERING THE WORLD OF WORK,
 HELPING PEOPLE AND ORGANISATIONS ACHIEVE LASTING IMPACT.
 
 Hays is a leading global professional recruiting group, the expert at recruiting qualified, professional and skilled people worldwide, being the market leader in the UK and Asia Pacific and one of the market leaders in Continental Europe and Latin America. 
 
 Hays operates across the private and public sectors, dealing in permanent positions, contract roles and temporary assignments.
', 3);
INSERT INTO my_laravel.joblists (job_name, job_rank, job_company, job_des, company_des, jobcategory_id) VALUES ('Sales Executive', 4, 'Autorola Australia  Company Location Hawthorn East, Victoria, Australia', 'Autorola Australia is Australia’s fastest growing online automotive remarketing company.

Head office is located in the leafy suburb of Hawthorn East, Melbourne. Autorola offers vendors and buyers an efficient online sales platform supported by focused and highly motivated account managers and sales team.

We are looking for an enthusiastic and confident sales account Executive to join our fleet team to assist with selling and auction preperation, buyer contact and buyer development, administration of certain auctions and general day to day functions in our office.', 'Operating across Australia and the region with On Line auctions and vehicle remarketing services specifically for automotive products and clients- servicing vehicle manufacturers and vehicle importers; lease, rental and finance institutions, Major insurers and self insurered operators and a large number of other coporate clients. Europes and now Australia''s fastest growing On Line vehicle remarketing service.', 3);
INSERT INTO my_laravel.joblists (job_name, job_rank, job_company, job_des, company_des, jobcategory_id) VALUES ('Sales Account Manager', 5, 'Eco Outdoor  Company Location Richmond, Victoria, Australia', 'Job description

Account Manager - Sales


Eco Outdoor, one of Australia’s premier retailers of Architectural flooring, walling and outdoor furniture products has an opportunity available for a dynamic and ambitious individual to join their Melbourne team.

You''d be working in our Richmond architectural showroom servicing designers, architects, and interior designers, as well as supporting retail consumers and our business development team driving sales of our architectural flooring & walling products – as well as outdoor furniture.', 'We are Eco Outdoor, one of Australia''s leading retailers of architectural flooring and walling products.  Eco Outdoor has an enviable reputation within the industry as the "go to" company for architects and designers when selecting walling and flooring for any residential and commercial projects.', 3);
INSERT INTO my_laravel.joblists (job_name, job_rank, job_company, job_des, company_des, jobcategory_id) VALUES ('Sales Representative', 6, 'IT Xchange  Company Location Melbourne, Australia', 'Xchange Technology Group (XTG), a leader in the computer resale, remarketing and rental business has an opening for a Sales Representative to join the team in Australia. XTG has over 200 employees in USA, Canada, United Kingdom, Japan, Australia and China.

The Sales Representative provides post-sales support for Account Executives, as well as generating new business through telemarketing. The amount of time devoted to sales support declines as the Sales Support Representative’s portfolio of new business grows.', 'Xchange Technology Group (XTG), established in 1996, is a multinational corporation with regional offices in Raleigh, N.C., USA; Mississauga, Canada; Paisley, UK; Tokyo, Japan; Macau, China; and Victoria, Australia. It oversees and manages three divisions that provide resale, rental and remarketing technology product and service solutions. XTG specializes in technology lifecycle management, designed to dramatically improve the return on customers’ technology investments at all stages of the lifecycle. XTG’s technology rental division provides computer sourcing, short-term leasing and flexible IT/audio/visual rental offerings to customers through superior online services and technical support. ', 3);
INSERT INTO my_laravel.joblists (job_name, job_rank, job_company, job_des, company_des, jobcategory_id) VALUES ('Internal Sales Representative', 7, 'IMI Precision Engineering  Company Location Rowville, Victoria, Australia', 'IMI Precision Engineering is a world leader in motion and fluid control technologies. Wherever precision, speed and engineering reliability are essential, we deliver exceptional solutions which improve the productivity and efficiency of our customers'' equipment.

Part of IMI plc, we have a sales and service network in 75 countries, as well as manufacturing capability in the USA, Germany, China, UK, Switzerland, Czech Republic, Mexico and Brazil. We support this with our global centers of technical excellence and facilities for CFD design and R&D testing', 'We are a world leader in motion and fluid control technologies. Wherever precision, speed and engineering reliability are essential, we deliver exceptional solutions which improve the productivity and efficiency of our customers’ equipment. As a business, we aim to understand our customers’ challenges. We then connect our products, people and expertise in order to deliver exceptional service and solutions. These improve the performance of our customers’ machinery. We call this Engineering GREAT, and we deliver it to customers through a world-class portfolio of high performance products, through close partnerships and problem-solving, and through a global network of support which ensures reliable local delivery, all over the world. Engineering GREAT is in our DNA. It runs through all of our work, every one of our businesses, and in each and every action we take. At the heart of everything we do, Engineering GREAT means combining the best and most appropriate products, technologies and expertise from across our portfolio, and using them to create something life-changing, long-lasting and world-class. We’re investing in innovation and the smartest global systems so customers get GREAT solutions and a unique service that is totally engineered around them. Part of IMI plc, we have a sales and service network in 75 countries, as well as manufacturing capability in the USA, Germany, China, UK, ', 3);
INSERT INTO my_laravel.joblists (job_name, job_rank, job_company, job_des, company_des, jobcategory_id) VALUES ('Outside Sales Representative', 8, 'Big Ass Fans  Company Location Melbourne, Australia', 'Consistent, on-going face to face customer management for Commercial/Industrial projects, including collection of relevant information, as well as dimensions and details necessary to make airflow and lighting recommendations for the relevant project. Primary contacts will be facility managers and other decision makers who are seeking airflow and lighting solutions for their commercial / industrial facilities.

Completion of Site Visit/cold call notes within 48 hours of completion of visits. Majority should be completed within 24 hours so a quote/presentation can be scheduled within the shortest timeframe possible.', 'In 1999, the Big Ass Fan Company was born. Kind of. Then called the HVLS Fan Co. (that’s High Volume, Low Speed—catchy, right?), we first made our mark selling massive ceiling fans that spun slowly but moved astounding amounts of air. The fans kept large spaces that lacked air conditioning, such as factories and dairy barns, feeling cool and comfortable—and soon enough, plenty of other customers wanted in. Things moved fast after that (and kept moving). Only a few years later, we officially changed our name after customers kept calling and asking if we made “those big-ass fans.” When churches wanted to install fans to keep congregations comfortable, we developed the first silent fan motor to meet their needs.   We created a residential fan that blew away ENERGY STAR® ratings and won awards worldwide. In 2014, we had the bright idea to create an LED fixture so tough you can drive a truck over it, launching a division appropriately called Big Ass Light™.  ', 3);
INSERT INTO my_laravel.joblists (job_name, job_rank, job_company, job_des, company_des, jobcategory_id) VALUES ('Sales Engineer', 9, 'Skedulo  Company Location Melbourne, Victoria, Australia', 'Skedulo is the leading mobile workforce scheduling application built on the Salesforce platform. Skedulo helps companies around the world transform the way they manage and schedule their mobile workforce teams in healthcare, telecommunications, hospitality, manufacturing, field service, and more. With our beautiful, easy to use web and mobile application, thousands of workers in the field are scheduled at the right place and at the right time with all the information they need to successfully complete their work.', 'Skedulo builds mobile-first applications that schedule and empower workers across the globe. The practical application of technology to enable big ideas is what excites us.We strive to make a lasting impact on the businesses we work with. Company and culture, customers and product; these are what we care about most. We are seasoned and passionate advisors, architects, designers, engineers, strategists and builders of great things.', 3);
INSERT INTO my_laravel.joblists (job_name, job_rank, job_company, job_des, company_des, jobcategory_id) VALUES ('Media Sales Consultant', 10, 'Meltwater  Company Location Melbourne, Australia', 'Are you passionate about sales and looking to join a global tech company with award winning software? Meltwater currently has a role where you can bring your negotiation skills to next level and learn the ins and outs of media intelligence.

Openings available in our Melbourne office at Rialto Towers. Apply direcly on our company careers website today!

As a Media Sales Consultant, you will become an expert on media intelligence and a whole range of industries/companies you didn''t even know existed - from universities and local government departments to ASX 200 companies. You will be responsible for the entire sales process, from prospecting to product demonstrations to bringing clients onboard yourself – getting all of the credit for your hard work!', 'Founded in Oslo in 2001 before moving our headquarters to San Francisco in 2006, Meltwater is the global leader in media intelligence, with over 1,100 employees globally and 24,000 clients. Our innovative products help businesses extract insights from billions of online conversations and articles – we call it Outside Insight.  Rare CultureFor over a decade, Meltwater has maintained a very rare culture, based on a foundation and belief in people and the potential they possess, regardless of experience. Like many entrepreneurially focused companies, Meltwater employees embody the work-hard, play-hard spirit. Whether you meet an employee from Sydney, or Hong Kong, you will likely discover many similarities in terms of their achievements, focus and superior communication skills. Our office spaces are collaborative, open working environments in which team work, learning and fun are the day-to-day norms. Each office consists of a number of small teams, ensuring that all of our employees have easy and frequent exposure to their managers and can quickly learn from those around them. ', 3);
INSERT INTO my_laravel.joblists (job_name, job_rank, job_company, job_des, company_des, jobcategory_id) VALUES ('Real Estate Lawyer', 1, 'Ashurst  Company Location Melbourne, AU', 'About Ashurst:
Ashurst is a leading global law firm with a history spanning almost 200 years, and clear strategy for our future growth. Our in-depth understanding of our clients and commitment to providing exceptional standards of service have seen us become a trusted adviser to local and global corporates, financial institutions and governments in all areas of commercial law. To find out more please visit here .', 'Ashurst is a leading global law firm. We advise local and international corporations, financial institutions and government clients.   Global coverage: We have 25 offices in 15 countries and a best-friend referral relationship with an Indian law firm. With over 400 partners and 1,700 lawyers in total, we offer the international insight of a global network combined with local market knowledge.', 4);
INSERT INTO my_laravel.joblists (job_name, job_rank, job_company, job_des, company_des, jobcategory_id) VALUES ('Real Estate Officer/ Assistant', 2, 'CitiPower and Powercor  Company Location Melbourne, Australia', 'About the role:

We currently have an opportunity for a 12 Month Maternity Contract for a Real Estate Officer to be an integral part of our Real Estate team based at our Melbourne CBD Head Office.

Reporting to the Manager Real Estate, you will be required to undertake a variety of tasks predominantly focused on preparation of property related documents and titles office applications, attending the Land Titles Office to register dealings on title and effectively communicating your detailed understanding of property related transactions to internal and external customers.', 'About CitiPower & Powercor: CitiPower and Powercor Australia are electricity distributors and supply power to more than one million Victorians. We own and manage the technology - poles, wires, meters and distributed technologies such as storage - that deliver electricity to homes and businesses within Melbourne’s CBD, its suburbs and across central and western Victoria.  Your career with CitiPower and Powercor:   When you join our business, your work-life balance and career development are high priorities. We place emphasis on your development through diverse training programs, leadership courses and internal opportunities.   Some of our benefits: Exposure to industry leading practices within a strong and stable company A great incentives package including an annual performance bonus, health and fitness subsidy, salary packaging options and much more….', 4);
INSERT INTO my_laravel.joblists (job_name, job_rank, job_company, job_des, company_des, jobcategory_id) VALUES ('Legal Secretary - Projects & Real Estate', 3, 'King & Wood Mallesons  Company Location Melbourne, Australia', 'We are looking for an experienced secretary with a background in Property and Real Estate with a high volume output to join our team.

Legal Secretary


Melbourne
Full-time

About you

Supporting a Partner and two Solicitors, you will be dedicated, proactive and able to provide a range of secretarial and administrative assistance in a timely and efficient manner.', 'Recognised as one of the world’s most innovative law firms, King & Wood Mallesons offers a different perspective to commercial thinking and the client experience. With access to a global platform, a team of over 2000 lawyers in 26 locations around the world, works with clients to help them understand local challenges, navigate through regional complexity, and to find commercial solutions that deliver a competitive advantage for our clients. ', 4);
INSERT INTO my_laravel.joblists (job_name, job_rank, job_company, job_des, company_des, jobcategory_id) VALUES ('Sales Manager - Real Estate', 4, 'sharonbennie - Specialist Property Recruitment  Company Location Sydney, Australia', 'Regional Sales Manager - to $200K


$100K - $150K Base neg.
No Selling
Leading Brand
Coaching & Accountability Focus
Listed exclusively with sharonbennie', 'About Us: Established over 11 years ago, sharonbennie is a leader in the Property / Real Estate recruitment space. Roles that we specialise in include:   General Managers / Regional Managers / Sales Managers Sales Assistants / Sales Consultants Prospectors / Telemarketers / Copywriters  Property Managers / Facilities Managers / Asset Managers / Strata Managers  Development Managers / Assistant DM’s / Project Managers / Site Managers  Contract Administrators  Property Valuers / Mortgage Brokers  Building Managers / Caretakers  Marketing Staff / Marketing Managers  Letting Executives / Business Development  Financial Managers / Bookkeepers / Trust Accountants  Receptionists / Assistants   Follow our company page to stay in touch with new roles: http://www.linkedin.com/company/sharon-bennie---specialist-property-recruitment', 4);
INSERT INTO my_laravel.joblists (job_name, job_rank, job_company, job_des, company_des, jobcategory_id) VALUES ('CRM Advisor Real Estate', 5, 'Suncorp Group  Company Location Sydney, AU', 'CRM Advisor Real Estate
A diverse and interesting variety of work
Collaborate across teams and build strong relationships
Brisbane or Sydney Location
Suncorp is an organisation on the move. Our commitment to our people has spurred a culture where leaders are empowered to make decisions and people are able to succeed in a supportive environment that rewards ambition. Combined with a diversified mix of businesses, Suncorp provides a broad range of career development opportunities across a vast array of business areas. The purpose of the CRM Advisor, Real Estate is to contribute to Real Estate’s overarching goal to provide expertise in the design and delivery of workplace solutions aligned to the Group’s strategic business agenda.', 'The Suncorp Group includes some of Australia and New Zealand’s leading general insurance, banking, life insurance and superannuation brands. We help millions of people reach their goals, build their wealth, protect what is special to them, and provide for their future.  ', 4);
INSERT INTO my_laravel.joblists (job_name, job_rank, job_company, job_des, company_des, jobcategory_id) VALUES ('Finance Solutions Analyst - Australian Real Estate', 6, 'QIC  Company Location Brisbane', 'The Opportunity

We currently have a full time open term opportunity for an experienced Finance Solutions Analyst who enjoys identifying and driving continuous improvement. This Brisbane based role forms part of our high performing Financial Solutions team, responsible for providing Finance application support and advisory services across the QIC Group, as well as solution and process design for the Finance division.', 'We were born with one objective – to deliver investment outcomes for our clients. Created in 1991 by the Queensland government to serve its long term investment responsibilities, we have grown into a Global Diversified Alternatives business. 
 ', 4);
INSERT INTO my_laravel.joblists (job_name, job_rank, job_company, job_des, company_des, jobcategory_id) VALUES ('Real Estate Consultant', 7, 'MSCI Inc.  Company Location Sydney', 'An excellent opportunity to grow your career has become available as MSCI is looking to expand the real estate client coverage team. The role will be a member of the broader APAC business focusing on the Australia & New Zealand markets. The real estate client coverage team is the primary point of contact for clients and users of real estate products and services and a key link between clients and other departments of MSCI. So while working in a small team locally, the Client Consultant will need to function as a hub for several departments globally to ensure the best possible client service is provided. The Client Consultant is responsible for understanding property market fundamentals and directly responding to a wide variety of property performance analytics, methodology issues, implementation, ', 'MSCI Inc. is a leading provider of investment decision support tools to investors globally, including asset managers, banks, hedge funds and pension funds. MSCI products and services include indexes, portfolio risk and performance analytics, and governance tools.', 4);
INSERT INTO my_laravel.joblists (job_name, job_rank, job_company, job_des, company_des, jobcategory_id) VALUES ('Real Estate Advisory - Manager - Melbourne', 8, 'PwC Australia  Company Location Melbourne, AU', 'Work on complex and high profile transactions
Benefit from a flexible working environment
Join a team of entrepreneurial team with a dynamic culture
PwC Australia helps organisations and individuals create the value they’re looking for. With over 6,000 staff nationally we are a member firm of the PwC network globally and one of Australia’s leading professional services firms.', 'At PwC asking questions is at the heart of what we do when helping clients that range from the largest, global organisations, to governments and other not-for-profit organisations, to start-ups. We take the time to listen and understand their goals and their competitive and regulatory environment. And then we tap into our global network, deep industry expertise, and strong judgement and experience to help each client create the kind of value they are looking for.', 4);
INSERT INTO my_laravel.joblists (job_name, job_rank, job_company, job_des, company_des, jobcategory_id) VALUES ('Real Estate Agent', 9, 'Black Diamondz Property Concierge  Company Location Sydney, Australia', 'We are seeking individuals who understand and thrive off of the demands of high-end/luxury Real Estate, are looking for longevity in their career and to be a part of a driven and successful team!', 'Working for Black  as a Real Estate Agent; Work with and learn from professional and successful entrepreneurs who are leaders in their field Impressive commissions and flexible salary negotiations Convenient CBD location The opportunity to sell some of Sydney''s premier real estate to both local and international buyers  Want to know what it''s really like to work at Black Diamondz - take a look at the following link https://www.youtube.com/watch?v=Dchzm5rgORc', 4);
INSERT INTO my_laravel.joblists (job_name, job_rank, job_company, job_des, company_des, jobcategory_id) VALUES ('Residential Property Manager', 10, 'Knight Frank Australia  Company Location Melbourne, Australia', 'Flexible working conditions and no Saturday''s!!!
All properties located close to each other
Based in Collins Street with car space, laptop and mobile phone provided


Knight Frank is recognised as a leader in property consultancy throughout the world, operating in 58 countries and employing more than 13,000 people worldwide. In Australia, Knight Frank employs approximately 1,000 professionals in 24 offices. Knight Frank represents its clients in both commercial and residential markets, offering professional, agency and consultancy services.



The Role

We are looking for an experienced Residential Property Manager, or someone in a property support role looking to take the next step! Managing your portfolio of properties, you will have the opportunity to work in a fun, organised, corporate environment and we are also open to the right person working part-time 4 days per week. You will be responsible for all property tasks from the tenant moving in through to vacate, including:

Manage client relationships
Conduct condition reports and routine inspections.
Manage maintenance issues
Rental Arrears
Execute lease and rent reviews
Answer queries promptly as required
Onboarding of new buildings – some limited leasing may be required.


The Person

Your work style will be thorough and your communication skills professional yet friendly. You will also be able to work autonomously. In addition, you will have:

Previous experience as a Residential Property Manager or have worked in an Real Estate agency
An Agent''s Representative Certificate
A valid driver''s license plus a reliable and presentable vehicle
Professional presentation
High level of organisational and coordination skills
Excellent attention to detail
Self-motivated and ability to work autonomously
Ability to problem solve and stay calm under pressure


What''s in it for you?

If this sounds like you, come and join us! You will be rewarded with the opportunity to be part of a well-known global brand and to develop your career with an industry leader. In addition, you will work in a professional environment, flexible conditions, laptop, company phone, a modern new office plus much more!

With a newly launched people-focused vision and strategy, there is no better time for a passionate, friendly Property Manager to join Knight Frank Australia. This is a great opportunity to develop your career in a supportive, thriving team.

To apply for this outstanding opportunity please click the ‘Apply'' button below and include a covering letter with your CV.

Please apply directly, recruitment agency applications will not be accepted.

', 'Knight Frank is recognised as a leader in property consultancy throughout the world, operating in 58 countries and employing more than 13,000 people worldwide. In Australia, Knight Frank employs approximately 1,000 professionals in 24 offices. Knight Frank represents its clients in both commercial and residential markets, offering professional, agency and consultancy services.', 4);