UPDATE joblists SET job_name = 'Senior Software Engineer-3D Computer Vision', job_rank = 1, job_company = 'Nearmap', job_des = 'Nearmap captures and processes massive quantities of high-resolution aerial imagery using world-leading automated technology. Our latest camera systems deliver rich 3D capability and the potential for a large array of new products and analysis. We are loo', company_des = 'Nearmap is a global leader in the provision of geospatial map technology for business, enterprises and government customers. As a truly innovative company for technical disruption, Nearmap holds over a dozen international patents and has developed a solut', jobcategory_id = 2 WHERE id = 1;
UPDATE joblists SET job_name = 'Power Programmer', job_rank = 2, job_company = 'Infosys', job_des = 'Short Description: As a Power Programmer, you will have the opportunity to work on Large Scale Digital Platforms and market places on complex engineering projects using cloud native architecture. This is an opportunity for a hands on developer to work on ', company_des = 'About us   Infosys is a global leader in consulting, technology, and outsourcing and next-generation services. We enable clients in more than 50 countries to outperform the competition and stay ahead of the innovation curve. With US$9.50 bn in FY16 revenu', jobcategory_id = 2 WHERE id = 2;
UPDATE joblists SET job_name = 'Service Desk Engineer', job_rank = 3, job_company = 'Viatek Pty Ltd ', job_des = 'We are looking for highly motivated, driven Service Desk Engineers - Level 1, to join our growing teams in Melbourne and Sydney, supporting our managed services contracted clients.

The role of the Service Desk Engineer - Level 1 is critical to the grow', company_des = 'Viatek Technology has an enviable reputation for high standards in IT solutions and service delivery.  We have grown rapidly, and have embraced the cloud age with our own cloud services, we are continually expanding thanks to a portfolio of sought-after t', jobcategory_id = 2 WHERE id = 3;
UPDATE joblists SET job_name = 'Maintenance Technician', job_rank = 4, job_company = 'Kapsch TrafficCom AG  Company Location Melbourne, Australia', job_des = 'We have an opportunity for an experienced Maintenance Technician to join our professional team in Melbourne.
The technician will, as part of a team, provide technical service, ongoing support and maintenance of the tolling systems.
You will be actively ', company_des = 'Kapsch TrafficCom is a provider of intelligent transportation systems (ITS). Our systems employ information and communication technologies to support and optimize road transportation, including infrastructure, vehicles, users and industry. Our core busine', jobcategory_id = 2 WHERE id = 4;
UPDATE joblists SET job_name = 'Technical Support Representative - (Japanese/English)', job_rank = 5, job_company = 'OpenTable  Company Location Melbourne, AU', job_des = 'Reporting to the Technical Support Supervisor, the Technical Support Representative will be responsible to provide customer support to customers, answering complex questions on function and usage of products via telephone, email and/or Internet. S/he will', company_des = 'We love what can happen around the restaurant table. Since 1998, we’ve been committed to empowering that experience. From helping restaurants grow and run their businesses, to enabling diners to discover and book the perfect table every time they dine, ou', jobcategory_id = 2 WHERE id = 5;
UPDATE joblists SET job_name = 'IT Manager', job_rank = 6, job_company = 'Hare & Forbes Machineryhouse  Company Location Northmead, New South Wales, Australia', job_des = 'The Position

Located at our Northmead Head Office, we are seeking candidates for a newly created role for an IT Manager with a twist of Digital Marketing Management.

The Successful Candidate

The successful candidate will have experience in a Mana', company_des = 'Hare & Forbes Machineryhouse have been supplying NEW & USED Workshop & Engineering Equipment since 1930.  Foundation principles have not changed to this date - to offer one of Australia''s most extensive range of workshop machinery and machine tool accesso', jobcategory_id = 2 WHERE id = 6;
UPDATE joblists SET job_name = 'Logistics Technician', job_rank = 7, job_company = 'Interactive Pty Ltd  Company Location Sydney, AU', job_des = 'Are you looking for your next great career move, a place where you can thrive and make a difference? At Interactive we pride ourselves on having a great work culture and providing the best customer experience in the industry. That''s how we''ve achieved the', company_des = 'Established in 1988, Interactive is one of Australia’s leading IT service providers. We are the supplier of choice for critical Cloud and Managed Services, Data Centre, Business Continuity and Hardware Maintenance for more than 2000 of Australia’s most su', jobcategory_id = 2 WHERE id = 7;
UPDATE joblists SET job_name = 'Desktop Technician', job_rank = 8, job_company = 'Marsh & McLennan Companies  Company Location Melbourne, AU', job_des = 'The Distributed Operations (DO) team provides overall operational support to the Pacific fleet of desktops and associated services that are hosted in the Pacific offices.', company_des = 'Scientific Games is a leading innovator in the global lottery and regulated gaming industries. Beginning with the breakthrough technology that launched the world’s very first secure instant lottery game in 1974, the company has continued to advance the games, technology, programs, marketing research and security that have been a driving force behind the success of more than 300 customers on six continents over the last 40 years.  Through the knowledge and experience of over 3,500 employees, Scientific Games serves customers from advanced-technology manufacturing and operational facilities in North America, South America, Europe, Asia and Australia, with additional facilities located throughout the U.S. and around the world based on customer requirements.', jobcategory_id = 2 WHERE id = 8;
UPDATE joblists SET job_name = 'Senior SQA Engineer', job_rank = 9, job_company = 'Scientific Games  Company Location Sydney, AU', job_des = 'This position is responsible for developing and executing tests on new and existing products to ensure that they meet the requisite functional, technical, and regulatory compliance and maintain high overall product quality. Interface with Game/OS Development and other Product Development staff to resolve issues in a timely manner. Also responsible for having proficient understanding of the software test methodologies and procedures in order to ensure testing efficiency and high level of quality. Will participate in mentoring Associate SQA and SQA Engineers. Organize and lead inter-departmental project meetings.', company_des = 'Scientific Games is a leading innovator in the global lottery and regulated gaming industries. Beginning with the breakthrough technology that launched the world’s very first secure instant lottery game in 1974, the company has continued to advance the games, technology, programs, marketing research and security that have been a driving force behind the success of more than 300 customers on six continents over the last 40 years.  Through the knowledge and experience of over 3,500 employees, Scientific Games serves customers from advanced-technology manufacturing and operational facilities in North America, South America, Europe, Asia and Australia, with additional facilities located throughout the U.S. and around the world based on customer requirements.', jobcategory_id = 2 WHERE id = 9;
UPDATE joblists SET job_name = 'Helpdesk Analyst', job_rank = 10, job_company = 'Michael Page  Company Location Ultimo, AU', job_des = 'Permanent Full Time
Helpdesk Analyst
About Our Client
My client is a significant industry force today because of the principles established over 25 years ago.
Job Description
Provide Help Desk services to all users.
Creating materials for end-user frequently asked questions (FAQs).
Maintain and be familiar with system documentation and document control.
Under general supervision, provide technical software, hardware and network problem resolution to all computer users by performing question / problem diagnosis and guiding users through step-by-step solutions
Support Desktops and IT infrastructure including VOIP telecommunications, across 5 states including 6 to 10 remote site / project offices.', company_des = 'Welcome to the Michael Page global company profile.  Michael Page has four decades of expertise in professional services recruitment. We were established in London in 1976, and over this period we''ve grown organically to become one of the best-known and most respected consultancies, with an office network spanning six continents.   While size has its advantages, it doesn''t define us - the nature of our organic growth means that each new office is integrated into the region that it serves. It also means that as an employer looking to hire, or as a candidate aiming to grow your career you have the best of both worlds; a team that understands the market and geography you operate in, plus the resources and expertise of an international network at your disposal.  Our teams are broken down to focus on industry, assignment type, salary level and location, so your hiring requirements or job search will all be handled by a specialist who knows your sector inside-out. We are confident that our expertise can add value to your recruitment or job search process – get in touch to find out more.', jobcategory_id = 2 WHERE id = 10;